//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmployeeSalaries
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class EmployeeEntities : DbContext
    {
        public EmployeeEntities()
            : base("name=EmployeeEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<NameTable> NameTables { get; set; }
        public virtual DbSet<SalaryTable> SalaryTables { get; set; }
    
        public virtual ObjectResult<SearchDateByRange_Result> SearchDateByRange(Nullable<System.DateTime> begindate, Nullable<System.DateTime> enddate)
        {
            var begindateParameter = begindate.HasValue ?
                new ObjectParameter("begindate", begindate) :
                new ObjectParameter("begindate", typeof(System.DateTime));
    
            var enddateParameter = enddate.HasValue ?
                new ObjectParameter("enddate", enddate) :
                new ObjectParameter("enddate", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SearchDateByRange_Result>("SearchDateByRange", begindateParameter, enddateParameter);
        }
    
        public virtual ObjectResult<SalaryTable> SearchEmployeeSalaryByDateRange(Nullable<System.DateTime> begindate, Nullable<System.DateTime> enddate)
        {
            var begindateParameter = begindate.HasValue ?
                new ObjectParameter("begindate", begindate) :
                new ObjectParameter("begindate", typeof(System.DateTime));
    
            var enddateParameter = enddate.HasValue ?
                new ObjectParameter("enddate", enddate) :
                new ObjectParameter("enddate", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SalaryTable>("SearchEmployeeSalaryByDateRange", begindateParameter, enddateParameter);
        }
    
        public virtual ObjectResult<SalaryTable> SearchEmployeeSalaryByDateRange(Nullable<System.DateTime> begindate, Nullable<System.DateTime> enddate, MergeOption mergeOption)
        {
            var begindateParameter = begindate.HasValue ?
                new ObjectParameter("begindate", begindate) :
                new ObjectParameter("begindate", typeof(System.DateTime));
    
            var enddateParameter = enddate.HasValue ?
                new ObjectParameter("enddate", enddate) :
                new ObjectParameter("enddate", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SalaryTable>("SearchEmployeeSalaryByDateRange", mergeOption, begindateParameter, enddateParameter);
        }
    
        public virtual ObjectResult<SearchDate_Result> SearchDate(Nullable<System.DateTime> enteredDate)
        {
            var enteredDateParameter = enteredDate.HasValue ?
                new ObjectParameter("enteredDate", enteredDate) :
                new ObjectParameter("enteredDate", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SearchDate_Result>("SearchDate", enteredDateParameter);
        }
    
        public virtual ObjectResult<SearchDate_Result> SearchSalaryByDate(Nullable<System.DateTime> enteredDate)
        {
            var enteredDateParameter = enteredDate.HasValue ?
                new ObjectParameter("enteredDate", enteredDate) :
                new ObjectParameter("enteredDate", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SearchDate_Result>("SearchSalaryByDate", enteredDateParameter);
        }
    }
}
